apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
    spec:
      containers:
      - name: simple-node-container
        image: sajidjafri86/simple-node-app:latest
        ports:
        - containerPort: 3000
